### ISSUE TITLE
Weekly Extra Beer

### ISSUE THREAD

**Issue by TobiasScheuer** [ernest-koguc/sf-simulator#3]
as far as I can see, there is neither an option to go for/simulate the weekly extra beer, nor have I found any hints in your code for that. 
Is that implemented and if not, could you add it? One extra beer per week makes a difference over long periods

**Comment by ernest-koguc** [comment]
Hi,
Nice catch. It is indeed not included in the simulation. Experience formula (for **weekly**) was unknown for a bit of time so I decided to postpone the implementation. Since it was discovered, I will add this possibility soon, it's already on my TODO list.

**Comment by TobiasScheuer** [comment]
Ok. Thank you for info

**Comment by ernest-koguc** [comment]
I've added the support for weekly rewards now. Let me know if anything.

**Comment by TobiasScheuer** [comment]
That's great, thank you for adding it so quickly!

Am Fr., 29. März 2024 um 16:04 Uhr schrieb ernest-koguc <
***@***.***>:
